import { I18nProvider } from "@/lib/i18n";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"]} );

export const metadata: Metadata = {
  title: "Karnavo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr">
      <body
        className={cn(inter.className, "antialiased min-h-screen")}
      >
        <I18nProvider>{children}</I18nProvider>
      </body>
    </html>
  );
}
